### ISSUE TITLE
Faculty grid misbehavior

### ISSUE THREAD

**Issue by jassi-singh** [therealansh/iiit_sonepat_app#14]
There is a problem in a file having path: lib/pages/faculty_grid.dart<br>
Here faculty grid is not functioning properly<br>When tapped between two different images of faculty profile of any one faculty opens.<br>

**Comment by pulkit0795** [comment]
It can be solved by adding spacing around gridview elements with the use of below code
` Container(...
        child: GridView.count(..
                mainAxisSpacing: 8.0,
                crossAxisSpacing: 8.0,
                ))`

**Comment by Avi-504** [comment]
givving crossAxisSpacing as 8.0 will result pixel overflow on 19:9 display devices 
(4 pixels overflow) reduce crossAxisSpacing to value lower oerequal to 4

**Comment by Avi-504** [comment]
> It can be solved by adding spacing around gridview elements with the use of below code
> ` Container(... child: GridView.count(.. mainAxisSpacing: 8.0, crossAxisSpacing: 8.0, ))`
givving crossAxisSpacing as 8.0 will result pixel overflow on 19:9 display devices
(4 pixels overflow) reduce crossAxisSpacing to value lower or equal to 4

**Comment by therealansh** [comment]
is this issue resolved?

**Comment by therealansh** [comment]
[DEPRECATED] closing this issue
