### ISSUE TITLE
Add Validator in Login Form

### ISSUE THREAD

**Issue by therealansh** [therealansh/iiit_sonepat_app#39]
The Authentication form right now does not provide any validation for the form.
Add Validation in `ui/Auth/LoginPage/Auth.dart` (there is a TODO task) and validators are present in `constants/validators.dart`.  Use the right regex for the email.
If you wanna take up this issue let me know.

**Comment by VanshKela** [comment]
Do we have to implement validator from validators.dart in form in ui/Auth/LoginPage/Auth.dart?

**Comment by therealansh** [comment]
Yes @VanshKela validators are there in validators.dart. But the regex in emailValidator is for a general email. Try to make the regex for the college mail id. And implement these validators in the Form() in auth.dart. Also pass formKey.validate() method in onClick listener of Sign In.

**Comment by VanshKela** [comment]
Yes sir I did all that but didn't create a new regex though.

**Comment by therealansh** [comment]
> Yes sir I did all that but didn't create a new regex though.

try to write the regex as well

**Comment by VanshKela** [comment]
Okay sir
