### ISSUE TITLE
Error During Compilation

### ISSUE THREAD

**Issue by harshit54** [therealansh/iiit_sonepat_app#4]
![image](https://user-images.githubusercontent.com/13780335/85921112-4b3bbc80-b897-11ea-863e-ec0c3e9bca0b.png)

Their is an error but the app runs fine.

**Comment by therealansh** [comment]
Apparently, settings.gradle needs to be modified refer to [this](https://github.com/FirebaseExtended/flutterfire/issues/2599), might help

**Comment by harshit54** [comment]
@therealansh That kind of solves the problem. However there is still the other error.

![image](https://user-images.githubusercontent.com/13780335/85923842-0c643180-b8ac-11ea-87f6-337c53126db5.png)

I think this relates to [Issue#57311](https://github.com/flutter/flutter/issues/57311) of the official flutter repo, but it refers to this error being a fatal one, which is not the case here.

I am still closing the issue though as I believe that the solution will be posted on the official issue.

**Comment by pulkit0795** [comment]
Update your settings.gradle to -->
----------------------------------------------------------------------------------------------------------------


include ':app'

def flutterProjectRoot = rootProject.projectDir.parentFile.toPath()

def plugins = new Properties()
def pluginsFile = new File(flutterProjectRoot.toFile(), '.flutter-plugins')
if (pluginsFile.exists()) {
    pluginsFile.withReader('UTF-8') { reader -> plugins.load(reader) }
}

plugins.each { name, path ->
    def pluginDirectory = flutterProjectRoot.resolve(path).resolve('android').toFile()
    include ":$name"
    project(":$name").projectDir = pluginDirectory
}
